version: '3.8'

services:
  db:
    image: postgis/postgis:14-3.3
    container_name: ride_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d  # Mount script directory

  redis:
    image: redis:latest
    container_name: ride_redis
    restart: always
    ports:
      - "6379:6379"

  django:
    build: .
    container_name: ride_backend
    restart: always
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      REDIS_URL: redis://redis:6379/0
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    ports:
      - "8060:8060"
    volumes:
      - .:/app

volumes:
  postgres_data:
